### ISSUE TITLE
Does not work with command aliases

### ISSUE THREAD

**Issue by ChampiYann** [reegnz/jq-zsh-plugin#9]
First of all, this plugin is amazing!

However, it doesn't fully work with my workflow. I use it with `kubectl` and it does work properly with the full command, but, like many, i'm lazy and created the alias `k` for `kubectl`.
The problem is that when I use this syntax I get an empty REPL window.
Is there a way to configure the plugin, shell or alias to make aliases to work with this plugin?

**Comment by reegnz** [comment]
Thanks for the kind words! 🙇 

I also ran into that issue with aliases. I'm using the exact same `k` alias for `kubectl`, so I know your pain.
The problem itself comes from how `fzf` itself is handling executing it's preview command. It is just using `$SHELL -c` [when executing preview commands](https://github.com/junegunn/fzf/blob/master/src/util/util_unix.go).
Aliases, however are only loaded with an interactive zsh.
I think I will try to be more opinionated and handle shell on my own and wrap the preview command with an explicit call to the user's shell and pass the `-i` flag.

On the long run I'd prefer `fzf` to support passing flags to the shell instead, but the turnaround for that would be a bit long, so I'll do the shell wrapping first.

**Comment by reegnz** [comment]
OK, I just tried wrapping the shell. It works, with a significant caveat: you have to also accept the fact that it will load all of your .zshrc, so if you're using a lot of plugins (like I do), you'd not want to swallow the cost of that.

I'll see if I can find another alternative way (eg. loading an alternative .zshrc that only contains aliases) so that it's faster.

**Comment by reegnz** [comment]
@ChampiYann a workaround for your problem:
Instead of an alias, you should use a script on your PATH.

The spawning of an extra shell in a shell in a shell, and having it load your .zshrc on every keypress is something I probably won't pursue further, it's a limitation of fzf, and how shells and spawning subprocesses work in general. Since fzf is not shell-native, I don't think I'd be able to come up with a way for it to be able to use shell aliases.

As for the script on your PATH workaround:
```sh
#!/usr/bin/env bash
kubectl $@
```
And put that on your PATH somewhere (eg. into /usr/local/bin or whatever other place rocks your boat.
I put it under `$HOME/bin/k` and it works like a charm!

I'm gonna keep the issue open in case I do manage to run into a solution for aliases that doesn't prove to be a huge performance impact, but I won't be actively working on finding a solution for it.

For anyone knowing of a performant solution for this problem, PR-s are welcome.

**Comment by ChampiYann** [comment]
I might have found a solution actually.
I used a snippet from this answer: https://unix.stackexchange.com/a/150737
I added this at the start of the `jq-complete` function in the plugin file:
```shell
unset 'functions[_expand-aliases]'
functions[_expand-aliases]=$LBUFFER
(($+functions[_expand-aliases])) &&
    LBUFFER=${functions[_expand-aliases]#$'\t'}
```
I'm not entirely sure what it does so it will need some tweaking but looks like it uses the builtin zsh function `_expand-aliases` on the `LBUFFER` with some more shell magic I don't fully understand (my shell wizard level is not high enough...)

@reegnz, I'm hoping you can fit this in better than I did!

**Comment by reegnz** [comment]
That's a nice one, I'll contemplate on it. 👍

**Comment by ChampiYann** [comment]
I looked into it a bit more and my explanation is incorrect.
What this snippet does is leverage the fact that when a function is stored by zsh, it expands the aliases.
That's what it does in this command `functions[_expand-aliases]=$LBUFFER`.
It then regurgitates that function and removes the TAB at the beginning in this part: `LBUFFER=${functions[_expand-aliases]#$'\t'}`.
The first line of the snippet clears the functions, and this part: `(($+functions[_expand-aliases]))` checks if the function is created successfully.

**Comment by reegnz** [comment]
I would probably modify it in a way that the alias is only expanded when the command is passed to `jq-repl`, but I would not exand the alias in the shell line.
I'll try and add that functionality and fut it behind a feature flag for now: `JQ_ZSH_PLUGIN_EXPAND_ALIASES=1`.

**Comment by reegnz** [comment]
And thanks for the research @ChampiYann, you're awesome!

**Comment by reegnz** [comment]
@ChampiYann I've put the feature in a PR (#10), could you please have a look and try it out before I merge it?

**Comment by ChampiYann** [comment]
Looks good to me! Great work!

I noticed another bug, but it's unrelated to this feature.
The `0/0` line appears 3 times and covers the first `.`.
It looks like it's only esthetical cause the functionality looks ok.
![image](https://user-images.githubusercontent.com/28050794/141648724-83846941-b629-45e7-b3eb-bed2a0dc84ce.png)

I'll start a new issue if I notice wonky functionality due to that.

**Comment by reegnz** [comment]
@ChampiYann can you open a separate ticket for that one please? Thanks!

BTW I've merged the alias support, will make it the default after test-driving it for a few weeks with the env var.
